### ISSUE TITLE
Nabi는 이제 중단인건가요?

### ISSUE THREAD

**Issue by choehwanjin** [libhangul/nabi#2]
Nabi는 이제 중단인건가요?
데비안 최신 안정판에서 설치하면 백스페이스키를 누르고 있어도 연속 지우기가 안 됩니다. 눌렀다 뗏다 반복을 해줘야 해요.
우분투에서는 괜찮은디 데비안만 그러네요 ㅜ.ㅜ

_Originally posted by @RaniCloud in https://github.com/libhangul/nabi/pull/1#issuecomment-538310581_

**Comment by choehwanjin** [comment]
이슈 게시판이 없어서 pull request에 남기신 것 같아서 issue 게시판으로 옮겼습니다.

연속 지우기가 안되는 앱을 정확히 알려 주셔야 테스트가 됩니다.
어떤 프로그램인지, 그리고 버전은 어떻게 되는지 알려주세요.

**Comment by ghost** [comment]
앗, 답변 감사합니다. 다시 한 번 확인해 봤습니다.
debian 기반 mx linux를 쓸 때  nabi가 아예 백스페이스가 연속으로 다 안 먹혀서 최신 데비안 전체 문젠지 알고 이후 우분투에서만 썼었는데요.... 오늘 오리지날 데비안 다시 다 깔고 시도회 해보니까 괜찮네요. 아이고, 확인이 부족했던 점 죄송합니다. 이제 확실히 순정 데비안으로 와야겠습니다!!!

 
다만 KDE 데비안에 문제있습니다. KDE 기본 앱들 (돌핀 파일매니저. Kate 메모장. Konsole 터미널 등등) 모두 한영 전환이 안 되서 한글 사용이 안 됩니다. 다른 앱에서는 문제없구요. 일단 나비가 더 중요해서 딴 Desktop 쓰며는 되지만, kde 써보고 싶었던터라 아쉽네요. 버스터에서는 힘들겠죠?

좋으니입력기 만들어주셔서 감사합니다. 아이콘도 제일 이쁘고... 트레이 오른찍 메뇨에서 바로 바꿀 수 있는 것도 편하고, libhangul 신세벌식 바로 읽을 수 있는 기본앱도 나비 뿐이에요. 파폭 유저지만 크롬도 잘되서 너무 좋습니다~~~

**Comment by choehwanjin** [comment]
Qt5에서는 공식적으로 XIM 지원을 중단했다고 합니다. 따라서 KDE에서는 나비를 사용할 수 없겠습니다.
KDE에서 한글 입력을 하시려면 다른 입력기를 사용하셔야 할 것 같습니다.

https://lists.qt-project.org/pipermail/development/2013-January/009491.html

**Comment by ghost** [comment]
아, 그렇군요. KDE는 나중을 기약해야 겠네요. 바쁘신 와중에 답변 주셔서 너무나 감사합니다. 잘 사용하겠습니다.
