### ISSUE TITLE
How to get nabi working in QT apps?

### ISSUE THREAD

**Issue by bmansurov** [libhangul/nabi#3]
Hi, thanks for the great software. I'm trying to get nabi working on QT5 apps, but for some reason the icon never changes to 'A' from the butterfly. It works fine on Firefox and other apps, but in Goldendict or Anki, it doesn't work. Here's my config:

```
export XIM=nabi
export XIM_ARGS=
export XIM_PROGRAM="nabi"
export XMODIFIERS="@im=nabi"
export GTK_IM_MODULE=xim
export QT_IM_MODULE=xim
```

What should I do to get nabi workin on QT? Thanks!

**Comment by choehwanjin** [comment]
Qt5 does not support XIM. And nabi is XIM. So, you can't use nabi with Qt5.

See this link:
https://lists.qt-project.org/pipermail/development/2013-January/009491.html

**Comment by bmansurov** [comment]
OK, thanks.
